% isOpen  = exportToPPTX();
% if ~isempty(isOpen)
%     % If PowerPoint already started, then close first and then open a new one
%     exportToPPTX('close');
% end
% 
% exportToPPTX('open',fullfile('presentacion','dieTemplate.pptx'));

%% Encabezado

exportToPPTX('addslide','Layout','Encabezado de sección');
exportToPPTX('addtext','Tipo de Cambio Real','Position','title','fontsize',48);

%% TCR
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','L_Z.png'),...
            'Position', L2x2_UPPER_LEFT);
        
exportToPPTX('addpicture',...
            fullfile('src','presentacion','star.png'),...
            'Position', STAR_UPPER_LEFT);
        
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','L_Z_GAP.png'),...
            'Position', L2x2_LOWER_LEFT);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','DLA_Z.png'),...
            'Position', L2x2_UPPER_RIGHT);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','D4L_Z.png'),...
            'Position', L2x2_LOWER_RIGHT);

%% TCR SHORT
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','L_Z_short.png'),...
            'Position', L2x2_UPPER_LEFT);
        
exportToPPTX('addpicture',...
            fullfile('src','presentacion','star.png'),...
            'Position', STAR_UPPER_LEFT);
        
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','L_Z_GAP_short.png'),...
            'Position', L2x2_LOWER_LEFT);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','DLA_Z_short.png'),...
            'Position', L2x2_UPPER_RIGHT);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','D4L_Z_short.png'),...
            'Position', L2x2_LOWER_RIGHT);
        
        
%% TCR SUBPLOT
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'otras','TC_real_subplot.png'),...
            'Position', L1_SINGLE); 

% TCR SUBPLOT short
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'otras','TC_real_subplot_short.png'),...
            'Position', L1_SINGLE); 
%% TCR Componentes por corrimiento
if strcmp(folder_name{i}, 'v0')
        exportToPPTX('addslide');
        exportToPPTX('addpicture',...
                    fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                             'prediction_compared', sprintf('Comp_TCR_%s.png', MODEL.CORR_DATE_ANT)),... 
                    'Position', L1x2_LEFT);
        exportToPPTX('addpicture',...
                    fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                             'prediction_compared',sprintf('Comp_TCR_%s.png', MODEL.CORR_DATE)),...
                    'Position', L1x2_RIGHT);  

        % TCR Componentes por corrimiento short
        exportToPPTX('addslide');
        exportToPPTX('addpicture',...
                    fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                             'prediction_compared', sprintf('Comp_TCR_short_%s.png', MODEL.CORR_DATE_ANT)),... 
                    'Position', L1x2_LEFT);
        exportToPPTX('addpicture',...
                    fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                             'prediction_compared',sprintf('Comp_TCR_short_%s.png', MODEL.CORR_DATE)),...
                    'Position', L1x2_RIGHT);  

else
        exportToPPTX('addslide');
        exportToPPTX('addpicture',...
                    fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                             'prediction_compared',sprintf('Comp_TCR_%s.png', corr_date)),...
                    'Position', L1x2_LEFT);  
        exportToPPTX('addpicture',...
                    fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                             'prediction_compared', sprintf('Comp_TCR_%s.png', 'Alterno')),... 
                    'Position', L1x2_RIGHT);

        % TCR Componentes por corrimiento short
        exportToPPTX('addslide');
        exportToPPTX('addpicture',...
                    fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                             'prediction_compared',sprintf('Comp_TCR_short_%s.png', corr_date)),...
                    'Position', L1x2_LEFT);
        exportToPPTX('addpicture',...
                    fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                             'prediction_compared', sprintf('Comp_TCR_short_%s.png', 'Alterno')),... 
                    'Position', L1x2_RIGHT);                
    
end
                
%% Descomposición de shocks
if strcmp(folder_name{i}, 'v0')
        % Long
        exportToPPTX('addslide');
        exportToPPTX('addtext',sprintf('Corrimiento %s', MODEL.leg_ant),...
                     'Position',[0/2.54, 1.2/2.54, 16.93/2.54, 1.05/2.54],...
                     'HorizontalAlignment', 'center','fontsize',18); 
        exportToPPTX('addpicture',...
                    fullfile('plots',corr_date, folder_name{i},... 
                             'shock_dec','long','L_Z_GAP_shd_dsc.png'),... 
                    'Position',[0 2.51/2.54 16.93/2.54 14.98/2.54]);

        exportToPPTX('addpicture',...
                    fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                             'shock_dec','long','L_Z_GAP_shd_dsc.png'),...
                    'Position',[16.93/2.54 2.54/2.54 16.93/2.54 14.98/2.54]);  
        exportToPPTX('addtext',sprintf('Corrimiento %s', MODEL.leg_act),...
                     'Position',[17.04/2.54, 1.2/2.54, 16.93/2.54, 1.05/2.54],...
                     'HorizontalAlignment', 'center','fontsize',18);
        % Short
        exportToPPTX('addslide');
        exportToPPTX('addtext',sprintf('Corrimiento %s', MODEL.leg_ant),...
                     'Position',[0/2.54, 1.2/2.54, 16.93/2.54, 1.05/2.54],...
                     'HorizontalAlignment', 'center','fontsize',18); 
        exportToPPTX('addpicture',...
                    fullfile('plots',corr_date,folder_name{i},... 
                             'shock_dec','short','L_Z_GAP_shd_dsc.png'),... 
                    'Position',[16.93/2.54 2.51/2.54 16.93/2.54 14.98/2.54]);

        exportToPPTX('addpicture',...
                    fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                             'shock_dec','short','L_Z_GAP_shd_dsc.png'),...
                    'Position',[0 2.51/2.54 16.93/2.54 14.98/2.54]);  
        exportToPPTX('addtext',sprintf('Corrimiento %s', MODEL.leg_act),...
                     'Position',[17.04/2.54, 1.2/2.54, 16.93/2.54, 1.05/2.54],...
                     'HorizontalAlignment', 'center','fontsize',18);

% Excenarios
else
          % Long
        exportToPPTX('addslide');
       
        exportToPPTX('addtext',sprintf('Corrimiento %s', MODEL.leg_act),...
                     'Position',[0/2.54, 1.2/2.54, 16.93/2.54, 1.05/2.54],...
                     'HorizontalAlignment', 'center','fontsize',18);
        exportToPPTX('addpicture',...
                    fullfile('plots',MODEL.CORR_DATE,'v0',... 
                             'shock_dec','long','L_Z_GAP_shd_dsc.png'),...
                    'Position',[0 2.51/2.54 16.93/2.54 14.98/2.54]); 
                
                 
        exportToPPTX('addtext',MODEL.Esc.(folder_name{i}).name,...
                     'Position',[17.04/2.54, 1.2/2.54, 16.93/2.54, 1.05/2.54],...
                     'HorizontalAlignment', 'center','fontsize',18); 
        exportToPPTX('addpicture',...
                    fullfile('plots',corr_date,folder_name{i},... 
                             'shock_dec','long','L_Z_GAP_shd_dsc.png'),... 
                    'Position',[16.93/2.54 2.51/2.54 16.93/2.54 14.98/2.54]);
                 
        % Short
        exportToPPTX('addslide');
       
        exportToPPTX('addtext',sprintf('Corrimiento %s', MODEL.leg_act),...
                     'Position',[0/2.54, 1.2/2.54, 16.93/2.54, 1.05/2.54],...
                     'HorizontalAlignment', 'center','fontsize',18);
        exportToPPTX('addpicture',...
                    fullfile('plots',MODEL.CORR_DATE,'v0',... 
                             'shock_dec','short','L_Z_GAP_shd_dsc.png'),...
                    'Position',[0 2.51/2.54 16.93/2.54 14.98/2.54]); 
                
                 
        exportToPPTX('addtext',MODEL.Esc.(folder_name{i}).name,...
                     'Position',[17.04/2.54, 1.2/2.54, 16.93/2.54, 1.05/2.54],...
                     'HorizontalAlignment', 'center','fontsize',18); 
        exportToPPTX('addpicture',...
                    fullfile('plots',corr_date,folder_name{i},... 
                             'shock_dec','short','L_Z_GAP_shd_dsc.png'),... 
                    'Position',[16.93/2.54 2.51/2.54 16.93/2.54 14.98/2.54]);
end

%% Descomposicion de shocks (primera diferencia)
if strcmp(folder_name{i}, 'v0')
        % short
        exportToPPTX('addslide');
        exportToPPTX('addtext',sprintf('Corrimiento %s', MODEL.leg_ant),...
                     'Position',[0/2.54, 1.2/2.54, 16.93/2.54, 1.05/2.54],...
                     'HorizontalAlignment', 'center','fontsize',18); 
        exportToPPTX('addpicture',...
                    fullfile('plots',corr_date,folder_name{i},... 
                             'shock_dec','diff','L_Z_GAP_diff_shd_dsc.png'),... 
                    'Position',[0 2.51/2.54 16.93/2.54 14.98/2.54]);

        exportToPPTX('addpicture',...
                    fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                             'shock_dec','diff','L_Z_GAP_diff_shd_dsc.png'),...
                    'Position',[16.93/2.54 2.54/2.54 16.93/2.54 14.98/2.54]);  
        exportToPPTX('addtext',sprintf('Corrimiento %s', MODEL.leg_act),...
                     'Position',[17.04/2.54, 1.2/2.54, 16.93/2.54, 1.05/2.54],...
                     'HorizontalAlignment', 'center','fontsize',18);

% Excenarios
else
        % short
        exportToPPTX('addslide');
       
        exportToPPTX('addtext',sprintf('Corrimiento %s', MODEL.leg_act),...
                     'Position',[0/2.54, 1.2/2.54, 16.93/2.54, 1.05/2.54],...
                     'HorizontalAlignment', 'center','fontsize',18);
        exportToPPTX('addpicture',...
                    fullfile('plots',MODEL.CORR_DATE,'v0',... 
                             'shock_dec','diff','L_Z_GAP_diff_shd_dsc.png'),...
                    'Position',[0 2.51/2.54 16.93/2.54 14.98/2.54]); 
                
                 
        exportToPPTX('addtext',MODEL.Esc.(folder_name{i}).name,...
                     'Position',[17.04/2.54, 1.2/2.54, 16.93/2.54, 1.05/2.54],...
                     'HorizontalAlignment', 'center','fontsize',18); 
        exportToPPTX('addpicture',...
                    fullfile('plots',corr_date,folder_name{i},... 
                             'shock_dec','diff','L_Z_GAP_diff_shd_dsc.png'),... 
                    'Position',[16.93/2.54 2.51/2.54 16.93/2.54 14.98/2.54]);

end
%%
% exportToPPTX( ...
%     'save', ...
%     'prueba');
% exportToPPTX('close');  