% isOpen  = exportToPPTX();
% if ~isempty(isOpen)
%     % If PowerPoint already started, then close first and then open a new one
%     exportToPPTX('close');
% end
% 
% exportToPPTX('open',fullfile('presentacion','dieTemplate.pptx'));

%% Encabezado

exportToPPTX('addslide','Layout','Encabezado de sección');
exportToPPTX('addtext','Variables Externas','Position','title','fontsize',48);

%% PIB USA actualizado 
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','q_GDP_RW.png'),...
            'Position', L1x2_LEFT); 

% PIB USA actualizado short
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','q_GDP_RW_short.png'),...
            'Position', L1x2_RIGHT);      
%% Simulacion
exportToPPTX('addslide');

exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','L_GDP_RW.png'),...
            'Position', L2x2_UPPER_LEFT);

exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','L_GDP_RW_GAP.png'),...
            'Position', L2x2_LOWER_LEFT);
exportToPPTX('addpicture',...
            fullfile('src','presentacion','star.png'),...
            'Position', STAR_LOWER_LEFT);

exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','D4L_GDP_RW.png'),...
            'Position', L2x2_UPPER_RIGHT);

exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','D4S4L_GDP_RW.png'),...
            'Position', L2x2_LOWER_RIGHT);

% simulación short
exportToPPTX('addslide');

exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','L_GDP_RW_short.png'),...
            'Position', L2x2_UPPER_LEFT);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','L_GDP_RW_GAP_short.png'),...
            'Position', L2x2_LOWER_LEFT);
exportToPPTX('addpicture',...
            fullfile('src','presentacion','star.png'),...
            'Position', STAR_LOWER_LEFT);

exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','D4L_GDP_RW_short.png'),...
            'Position', L2x2_UPPER_RIGHT);

exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','D4S4L_GDP_RW_short.png'),...
            'Position', L2x2_LOWER_RIGHT);


%% Indice de precio de las Importaciones USA
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','m_ind_prec_impus.png'),...
            'Position', L1x2_LEFT);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','m_DLA_ind_prec_impus.png'),...
            'Position', L2x2_UPPER_RIGHT);
        
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','m_D4L_ind_prec_impus.png'),...
            'Position', L2x2_LOWER_RIGHT);


% Indice de precio de las importaciones USA short
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','m_ind_prec_impus_short.png'),...
            'Position', L1x2_LEFT);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','m_DLA_ind_prec_impus_short.png'),...
            'Position', L2x2_UPPER_RIGHT);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','m_D4L_ind_prec_impus_short.png'),...
            'Position', L2x2_LOWER_RIGHT);
        
%% Indice de precio de las Exportaciones USA
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','m_ind_prec_expus.png'),...
            'Position', L1x2_LEFT);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','m_DLA_ind_prec_expus.png'),...
            'Position', L2x2_UPPER_RIGHT);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','m_D4L_ind_prec_expus.png'),...
            'Position', L2x2_LOWER_RIGHT);


% Indice de precio de las Exportaciones USA short
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','m_ind_prec_expus_short.png'),...
            'Position', L1x2_LEFT);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','m_DLA_ind_prec_expus_short.png'),...
            'Position', L2x2_UPPER_RIGHT);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','m_D4L_ind_prec_expus_short.png'),...
            'Position', L2x2_LOWER_RIGHT);


%% Ponderador ALPHA
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','alpha.png'),...
            'Position', L1_SINGLE); %% Puede variar con el tamaño de la figura?

% Ponderador ALPHA short
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','alpha_short.png'),...
            'Position', L1_SINGLE); %% Puede variar con el tamaño de la figura?   

%% IPEI 
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','L_IPEI.png'),...
            'Position', L1x2_LEFT);       
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','D4L_IPEI.png'),...
            'Position', L1x2_RIGHT);
exportToPPTX('addpicture',...
            fullfile('src','presentacion','star.png'),...
            'Position', STAR_UPPER_RIGHT);
%short
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','L_IPEI_short.png'),...
            'Position', L1x2_LEFT);       
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','D4L_IPEI_short.png'),...
            'Position', L1x2_RIGHT);
exportToPPTX('addpicture',...
            fullfile('src','presentacion','star.png'),...
            'Position', STAR_UPPER_RIGHT);
        
        
%% Inflación externa = Subyacente PCE de EEUU 
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','L_CPI_RW.png'),...
            'Position', L2x2_UPPER_LEFT);
        
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','L_CPI_RW_GAP.png'),...
            'Position', L2x2_LOWER_LEFT);
        
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','DLA_CPI_RW.png'),...
            'Position', L2x2_UPPER_RIGHT);
        
exportToPPTX('addpicture',...
            fullfile('src','presentacion','star.png'),...
            'Position', STAR_UPPER_RIGHT);
        
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','D4L_CPI_RW.png'),...
            'Position', L2x2_LOWER_RIGHT);
%short
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','L_CPI_RW_short.png'),...
            'Position', L2x2_UPPER_LEFT);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PostProcessing','L_CPI_RW_GAP_short.png'),...
            'Position', L2x2_LOWER_LEFT);
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','DLA_CPI_RW_short.png'),...
            'Position', L2x2_UPPER_RIGHT);
exportToPPTX('addpicture',...
            fullfile('src','presentacion','star.png'),...
            'Position', STAR_UPPER_RIGHT);
        
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','D4L_CPI_RW_short.png'),...
            'Position', L2x2_LOWER_RIGHT);
        
%% TASA DE INTERÉS EXTERNA
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','RS_RW.png'),... 
            'Position', L1x2_LEFT);
exportToPPTX('addpicture',...
            fullfile('src','presentacion','star.png'),...
            'Position', STAR_UPPER_LEFT);
        
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','m_RS_RW.png'),...
            'Position', L1x2_RIGHT);  
% short
exportToPPTX('addslide');
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'prediction_compared','RS_RW_short.png'),... 
            'Position', L1x2_LEFT);
exportToPPTX('addpicture',...
            fullfile('src','presentacion','star.png'),...
            'Position', STAR_UPPER_LEFT);
        
exportToPPTX('addpicture',...
            fullfile('plots',MODEL.CORR_DATE,folder_name{i},... 
                     'PreProcessing','m_RS_RW_short.png'),...
            'Position', L1x2_RIGHT);  
%%
% exportToPPTX( ...
%     'save', ...
%     'prueba');
% exportToPPTX('close');  