%% Escenario que compara la versión del QPM con modificación en las remesas

%% Graficas


    % Pre-processing
    % monthly
    PreProcPlots_m(MODEL,...
        'Esc_add', {'v1', MODEL_ANT},...
        'tab_range_mm', tab_range_mm);
    
    % quarterly
    PreProcPlots_q(MODEL,...
        'Esc_add', {'v1', MODEL_ANT},...
        'tab_range', tab_range_source_data)
    % Graficas de simulación
    simPlots(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v1','prediction_compared'),...}
        'Esc_add', {'v1', MODEL_ANT.F_pred, MODEL.esc_col{2}},...
        'PlotList', get(MODEL.MF, 'xlist'),...
        'LegendsNames',{MODEL.leg_ant, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    
    % Post Procesamiento
    % Logaritmo/tendencia vs corr. Anterior
    PostPrLogsComp(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE,'v1', 'PostProcessing'),...
        'Esc',{'v0', MODEL.PostProc},...
        'Esc_add', {'v1', MODEL_ANT.PostProc.v0, MODEL.esc_col{2}},...
        'PlotList', pp_list,...
        'LegendsNames',{MODEL.leg_ant, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    % Variables en Niveles originales
    PostPrLevels(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v1','PostProcessing'),...
        'Esc_add', {'v1', MODEL_ANT.PostProc.v0, MODEL.esc_col{2}},...
        'PlotList', list_lev,...
        'Titles', tit_lev,...
        'LegendsNames',{MODEL.leg_ant, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    % Brechas
    PostPrGaps(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v1','PostProcessing'),...
        'Esc_add', {'v1', MODEL_ANT.PostProc.v0, MODEL.esc_col{2}},...
        'PlotList', list_gaps,...
        'LegendsNames',{MODEL.leg_ant, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    
    % Descomposición de choques para variables seleccionadas
    list = {'L_GDP_RW_GAP', 'DLA_CPI_RW', 'RS_RW', 'D4L_CPI_NOSUBY','L_GDP_GAP','DLA_CPIXFE', 'DLA_S', 'D4L_MB', 'RS',...
            'D4L_CPI', 'L_Z_GAP', 'D4L_VEL', 'RR', 'D4L_S', 'RMC', 'MCI', 'RSNEUTRAL'};
    
    % Long
    plot_shd_dsc(MODEL, MODEL_ANT.F_pred, MODEL_ANT.shd_dsc,...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v1','Shock_dec\long'),...
        'Rng', {},...
        'Variables',list)

    %short
    plot_shd_dsc(MODEL, MODEL_ANT.F_pred, MODEL_ANT.shd_dsc,...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v1','Shock_dec\short'),...
        'Rng', MODEL.DATES.hist_end-20:MODEL.DATES.hist_end+20,...
        'Variables',list)
    
    % Descomposición de chosques para variables seleccionadas
    % (Primeras diferencias)
    plot_diff_shd_dsc(MODEL,...
                  'variables', list,...
                  'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v1', 'Shock_dec', 'diff'),...
                  'Esc_add', {'v1', MODEL_ANT.shd_dsc, MODEL_ANT.F_pred});
    
    % Contribuciones
    contributions(MODEL,...
        'Esc_add', {'v1', MODEL_ANT.F_pred}, ... 
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v1', 'contributions') ...           
    );
              
    contributions(MODEL,...
        'Esc_add', {'v1', MODEL_ANT.F_pred}, ... 
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v1', 'diff_contributions'), ... 
        'Difference', true ...
    );         
    
    % Real exchange rate (subplot)
    tcr_subplot(MODEL,...
        'Esc_add', {'v1', MODEL_ANT.F_pred, MODEL.esc_col{2}},...
        'tab_range', tab_range,...
        'LegendsNames',{MODEL.leg_ant, MODEL.leg_act});
    
    % Money Velocity (subplot)
    vel_subplot(MODEL,...
        'tab_range', tab_range,...
        'Esc_add', {'v1', MODEL_ANT.PostProc, MODEL.esc_col{2}},...
        'tab_range', tab_range,...
        'LegendsNames',{MODEL.leg_ant, MODEL.leg_act},...
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v1', 'otras'));

disp('Escenario 1: ok');