%% Gráfica de remesas
figure;
        
set(gcf, ...
        'defaultaxesfontsize',14, ...
        'Position', [1 42.0182 1400.1 776.73] );

plot([MODEL.F_pred.REM_GDP]);

hold on
plot(MODEL.Esc.v6.pred.REM_GDP,...
     'color', MODEL.esc_col{6});
plot(MODEL.Esc.v7.pred.REM_GDP,...
    'color', MODEL.esc_col{7});
plot(MODEL.Esc.v8.pred.REM_GDP,...
    'color', MODEL.esc_col{8});
plot(MODEL.F.REM_GDP, 'color', [0 0 0]);

yline(15, '--', 'estado estacionario 15', 'LabelHorizontalAlignment', 'left',...
      'Fontsize', 12);
yline(18.8, '--', 'estado estacionario 18.8', 'LabelHorizontalAlignment', 'left',...
      'Fontsize', 12);

vline(qq(2024,3),...
      'LineWidth', 1,'LineStyle', '-.');
  
legend({'Base', MODEL.Esc.v6.name, MODEL.Esc.v7.name, MODEL.Esc.v8.name, 'Historia'},...
        'Location', 'Best');

title('Remesas como porcentaje del PIB', 'Comparativo entre escenarios');
    
v = axis;
text(v(1,1), 7.2,'Escenario Base y rho Remesas con estado estacionario 15% y Escenario ss Remesas y combinado con estado estacionario 18.8%',...
    'Fontsize', 11);

hold off

saveas( ...
    gcf, ...
    'Comparativo REM_GDP.png' ...
);

%% Gráfica de gap del producto

%% Gráfica de remesas
figure;
        
set(gcf, ...
        'defaultaxesfontsize',14, ...
        'Position', [1 42.0182 1400.1 776.73] );

plot([MODEL.F_pred.L_GDP_GAP]);

hold on
plot(MODEL.Esc.v6.pred.L_GDP_GAP,...
     'color', MODEL.esc_col{6});
plot(MODEL.Esc.v7.pred.L_GDP_GAP,...
     'color', MODEL.esc_col{7});
plot(MODEL.Esc.v8.pred.L_GDP_GAP,...
     'color', MODEL.esc_col{8});
plot(MODEL.F.L_GDP_GAP, 'color', [0 0 0]);

zeroline();
vline(qq(2024,3),...
      'LineWidth', 1,'LineStyle', '-.');

legend({'Base', MODEL.Esc.v6.name, MODEL.Esc.v7.name, MODEL.Esc.v8.name, 'Historia'},...
        'Location', 'Best');

title('Brecha del producto doméstico', 'Comparativo entre escenarios');

saveas( ...
    gcf, ...
    'Comparativo L_GDP_GAP.png' ...
);