%% Escenario Base para EP
%{
    Se realizan los ajustes para las variables principales
    Crecimiento Económico
    - D4_GDP_SM_ADJ
    - D4_GDP_SM_EP
    Inflación Total
    - D4L_CPI_ADJ
    - D4L_CPI_EP
    Depreciación Cambiaria interanual y Tipo de cambio relacionado
    - D4L_S_ADJ
    - D4L_S_EP
    - L_S_EP
    Tasa de interés líder de política monetaria
    - i_adj
    - i_EP
%}

%% Escenario Base para EP
% Historia hasta 2021Q4 y anclaje de IPEI de 2022Q1 hasta 2023Q2
EscBase = MODEL.F;

%% %%%%%%%%%%%%%%%% Creación de escenario alternativo %%%%%%%%%%%%%%%%%%%%%%


%{
% Asignación de anclaje
db4.i_adj(qq(2024,2):qq(2025,2)) = [0.5, 0.45, 0.40, 0.35, 0.25];
db4.D4L_CPI_ADJ(qq(2024,2):qq(2025,2)) = [1.5, 1.45, 1.40, 1.35, 1.25];
db4.D4_GDP_SM_ADJ(qq(2024,2):qq(2025,2)) = [1, 1.5, 1.40, 1.35, 1.25];
db4.D4L_S_ADJ(qq(2024,2):qq(2025,2)) = [-1, -1.5, -1.40, -1.35, -1.25];

% Creación de plan de simulación
planE4 = plan(QPM,fcstrng);
% Variables a exogenizar y endogenizar
% UNBALANCED TIME FIXING - ANTICIPATED SHOCKS BY CONSTRUCTION
planE4 = exogenize(planE4,{'i_adj'},qq(2024,2):qq(2025,2));
planE4 = exogenize(planE4,{'D4L_CPI_ADJ'},qq(2024,2):qq(2025,2));
planE4 = exogenize(planE4,{'D4_GDP_SM_ADJ'},qq(2024,2):qq(2025,2));
planE4 = exogenize(planE4,{'D4L_S_ADJ'},qq(2024,2):qq(2025,2));

planE4 = endogenize(planE4,{'SHK_i_adj'},qq(2024,2):qq(2025,2));
planE4 = endogenize(planE4,{'SHK_D4L_CPI_ADJ'},qq(2024,2):qq(2025,2));
planE4 = endogenize(planE4,{'SHK_D4_GDP_SM_ADJ'},qq(2024,2):qq(2025,2));
planE4 = endogenize(planE4,{'SHK_D4L_S_ADJ'},qq(2024,2):qq(2025,2));
%}
% Ejemplo
MODEL.DATES.E1_dates = MODEL.DATES.pred_start:qq(2025,4);
MODEL.Esc.v1.dbi = databank.clip(EscBase, MODEL.F_pred.L_CPIXFE.Start, MODEL.F_pred.L_CPIXFE.End);

% Ajustes para "dibujar" trayectorias
MODEL.Esc.v1.dbi.i_adj(MODEL.DATES.E1_dates) = [0.5, 0.45, 0.40, 0.35, 0.25, 0.25, 0.25];


% Plan de simulación
MODEL.Esc.v1.planSim = plan(MODEL.MF, MODEL.DATES.pred_start:MODEL.DATES.pred_end);
% Variable a endogenizar (shock propio?? No necesariamente)
MODEL.Esc.v1.planSim = endogenize(MODEL.Esc.v1.planSim,{'SHK_i_adj'},MODEL.DATES.E1_dates); 
% Variable a exogenizar (Anclaje)
MODEL.Esc.v1.planSim = exogenize(MODEL.Esc.v1.planSim,{'i_adj'},MODEL.DATES.E1_dates);

% Simulación.
MODEL.Esc.v1.pred = simulate(MODEL.MF,...
                  MODEL.Esc.v1.dbi,...
                  qq(2022,1):MODEL.DATES.pred_end,...
                  'plan',MODEL.Esc.v1.planSim,...
                  'anticipate',false,...
                  'DbOverlay=', true);

% Descomposición             
MODEL.Esc.v1.shd = simulate(MODEL.MF,...
                  MODEL.Esc.v1.pred,...
                  MODEL.DATES.hist_start:MODEL.DATES.pred_end,...
                  'anticipate',false,...
                  'contributions',true);



%% Post-Procesamiento de variables seleccionadas.
pp_list = {'L_MB', 'L_VEL', 'L_CPI_RW', 'L_CPI_RW_Q','L_Z', 'L_GDP', 'L_GDP_RW'};
list_nivel = {'L_S','L_MB'};

[MODEL.Esc.v1.pred.L_GDP_RW, MODEL.Esc.v1.pred.L_GDP_RW_BAR,...
    MODEL.Esc.v1.pred.D4L_GDP_RW, MODEL.Esc.v1.pred.DLA_GDP_RW,...
    MODEL.Esc.v1.pred.D4_GDP_RW_SM] = rec_GDP_RW(databank.clip(MODEL.PreProc.quarterly, MODEL.DATES.hist_start, qq(2021,4)),...
                                            MODEL.Esc.v1.pred,...
                                            MODEL.DATES);

MODEL = PostProcessing(MODEL,...
    'list',pp_list,...
    'list_niv', list_nivel,...
    'Esc',{'v1', MODEL.Esc.v1.pred});

%% Graficas

    % Pre-processing
    % monthly
    PreProcPlots_m(MODEL,...
        'Esc_add', {'v1', MODEL_ANT},...
        'tab_range_mm', tab_range_mm);
    
    % quarterly
    PreProcPlots_q(MODEL,...
        'Esc_add', {'v1', MODEL},...
        'tab_range', tab_range_source_data)
    % Graficas de simulación
    simPlots(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v1','prediction_compared'),...}
        'Esc_add', {'v1', MODEL.Esc.v1.pred},...
        'PlotList', get(MODEL.MF, 'xlist'),...
        'LegendsNames',{'Esc. Base', MODEL.leg_act},...
        'TabRange', tab_range...
        );
    
    % Post Procesamiento
    % Logaritmo/tendencia vs corr. Anterior
    PostPrLogsComp(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE,'v1', 'PostProcessing'),...
        'Esc',{'v0', MODEL.PostProc},...
        'Esc_add', {'v1', MODEL.PostProc.v1},...
        'PlotList', pp_list,...
        'LegendsNames',{'Esc. Base', MODEL.leg_act},...
        'TabRange', tab_range...
        );
    % Variables en Niveles originales
    PostPrLevels(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v1','PostProcessing'),...
        'Esc_add', {'v1', MODEL.PostProc.v1},...
        'PlotList', list_lev,...
        'Titles', tit_lev,...
        'LegendsNames',{'Esc. Base', MODEL.leg_act},...
        'TabRange', tab_range...
        );
    % Brechas
    PostPrGaps(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v1','PostProcessing'),...
        'Esc_add', {'v1', MODEL.PostProc.v1},...
        'PlotList', list_gaps,...
        'LegendsNames',{'Esc. Base', MODEL.leg_act},...
        'TabRange', tab_range...
        );
    
    % Descomposición de choques para variables seleccionadas
    list = {'L_GDP_RW_GAP', 'DLA_CPI_RW', 'RS_RW', 'D4L_CPI_NOSUBY','L_GDP_GAP','DLA_CPIXFE', 'DLA_S', 'D4L_MB', 'RS',...
            'D4L_CPI', 'L_Z_GAP', 'D4L_VEL', 'RR', 'L_CPI_RW', 'D4L_S'};
    
    % Long
    plot_shd_dsc(MODEL, MODEL.Esc.v1.pred, MODEL.Esc.v1.shd,...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v1','Shock_dec\long'),...
        'Rng', {},...
        'Variables',list)

    %short
    plot_shd_dsc(MODEL, MODEL.Esc.v1.pred, MODEL.Esc.v1.shd,...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v1','Shock_dec\short'),...
        'Rng', MODEL.DATES.hist_end-20:MODEL.DATES.hist_end+20,...
        'Variables',list)
    
    % Contribuciones
    contributions(MODEL,...
                  'Esc_add', {'v1', MODEL.Esc.v1.pred});
    
    % Real exchange rate (subplot)
    tcr_subplot(MODEL,...
        'Esc_add', {'v1', MODEL.Esc.v1.pred},...
        'tab_range', tab_range,...
        'LegendsNames',{'Esc. Base', MODEL.leg_act});
    
    % Money Velocity (subplot)
    vel_subplot(MODEL,...
        'tab_range', tab_range,...
        'Esc_add', {'v0', MODEL.PostProc},...
        'tab_range', tab_range,...
        'LegendsNames',{'Esc. Base', MODEL.leg_act},...
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v1', 'otras'));
