%% Escenario alterno 6
%{
    Este Escenario: Se anclan pronósticos de crecimiento para 8 trimestres. 
    
%}

%% Anclaje crecimiento económico diciembres (8 trimestres)

% Trimestres de anclaje
MODEL.DATES.E6_dates = MODEL.DATES.pred_start:MODEL.DATES.pred_start+5;

%% %%%%%%%%%%%%%%%% Creación de escenario alternativo %%%%%%%%%%%%%%%%%%%%%%
% Shocks del escenario base
shocks = MODEL.F*get(MODEL.MF, 'elist');
% Concatenación de bd con condiciones iniciales (MODEL.F) y shocks Esc.
% Libre
MODEL.Esc.v6.dbi = dboverlay(MODEL.F,shocks);

% Plan de simulación
MODEL.Esc.v6.planSim = plan(MODEL.MF, MODEL.DATES.pred_start:MODEL.DATES.pred_end);


% Imposición de anclajes de crecimiento

% Anclaje únicamente fines de año
MODEL.Esc.v6.dbi.D4S4L_GDP(MODEL.DATES.E6_dates) = [ ...
    NaN; 3.5; NaN; NaN; NaN; 3.5; ... 
];
anchor_dates = [qq(2024,4), qq(2025,4)];

% Anclaje trayectoria hasta 2025Q4
% MODEL.Esc.v6.dbi.D4S4L_GDP(MODEL.DATES.E6_dates) = MODEL.F_pred.D4S4L_GDP(MODEL.DATES.E6_dates); 
% MODEL.Esc.v6.dbi.D4S4L_GDP(qq(2024,4)) = 3.5; 
% MODEL.Esc.v6.dbi.D4S4L_GDP(qq(2025,4)) = 3.5; 
% anchor_dates = MODEL.DATES.E6_dates;

% Variable a exogenizar (Anclaje)
MODEL.Esc.v6.planSim = exogenize(MODEL.Esc.v6.planSim,{'D4S4L_GDP'}, anchor_dates);

% Variable a endogenizar (shock propio?? No necesariamente)
endog_vars = {'SHK_L_GDP_GAP'}; 
MODEL.Esc.v6.planSim = endogenize(MODEL.Esc.v6.planSim, endog_vars, anchor_dates); 


% Simulación.
MODEL.Esc.v6.pred = simulate(MODEL.MF,...
                  MODEL.Esc.v6.dbi,...
                  MODEL.DATES.pred_start:MODEL.DATES.pred_end,...
                  'plan',MODEL.Esc.v6.planSim,...
                  'anticipate', false, ...
                  'DbOverlay=', true);

% Descomposición             
MODEL.Esc.v6.shd = simulate(MODEL.MF,...
                  MODEL.Esc.v6.pred,...
                  MODEL.DATES.hist_start:MODEL.DATES.pred_end,...
                  'anticipate', false, ...
                  'contributions',true);

%% Inspección resultados escenario

simdb  = MODEL.Esc.v6.pred; 
% ressim  = [simdb.D4S4L_GDP simdb.S4L_GDP simdb.L_GDP simdb.PM_D4L_MB simdb.SHK_D4L_MB];
ressim  = [simdb.D4S4L_GDP simdb.S4L_GDP simdb.L_GDP simdb.L_GDP_GAP simdb.SHK_L_GDP_GAP]

%% Inspección resultados escenario libre

compdb  = MODEL.F_pred; 
% compsim = [compdb.D4S4L_GDP compdb.S4L_GDP compdb.L_GDP compdb.PM_D4L_MB compdb.SHK_D4L_MB]
compsim = [compdb.D4S4L_GDP compdb.S4L_GDP compdb.L_GDP compdb.L_GDP_GAP compdb.SHK_L_GDP_GAP]

%% Efectos sobre base monetaria y tasa

[simdb.RS simdb.D4L_MB compdb.RS compdb.D4L_MB]

%% Post-Procesamiento de variables seleccionadas.
% Desestacionalizar y obtener brechas y tendencias de estas variables
pp_list = {'L_MB', 'L_VEL', 'L_CPI_RW', 'L_IPEI_Q','L_Z', 'L_GDP', 'L_GDP_RW'};
% Recuperar niveles de estas variables
list_nivel = {'L_S','L_MB'};
                                        
MODEL = rec_GDP_RW(MODEL, 'Esc', 'v6');

MODEL = PostProcessing(MODEL,...
    'list',pp_list,...
    'list_niv', list_nivel,...
    'Esc',{'v6', MODEL.Esc.v6.pred});

%% Graficas

if graph_esc == true
    % Pre-processing
    % monthly
    PreProcPlots_m(MODEL,...
        'Esc_add', {'v6', MODEL_ANT},...
        'tab_range_mm', tab_range_mm);
    
    % quarterly
    PreProcPlots_q(MODEL,...
        'Esc_add', {'v6', MODEL_ANT},...
        'tab_range', tab_range_source_data)
    % Graficas de simulación
    simPlots(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','prediction_compared'),...}
        'Esc_add', {'v6', MODEL.Esc.v6.pred, MODEL.esc_col{2}},...
        'PlotList', get(MODEL.MF, 'xlist'),...
        'LegendsNames',{MODEL.esc_names{2}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    
    % Post Procesamiento
    % Logaritmo/tendencia vs corr. Anterior
    PostPrLogsComp(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE,'v6', 'PostProcessing'),...
        'Esc',{'v0', MODEL.PostProc},...
        'Esc_add', {'v6', MODEL.PostProc.v6, MODEL.esc_col{2}},...
        'PlotList', pp_list,...
        'LegendsNames',{MODEL.esc_names{2}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    % Variables en Niveles originales
    PostPrLevels(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','PostProcessing'),...
        'Esc_add', {'v6', MODEL.PostProc.v6, MODEL.esc_col{2}},...
        'PlotList', list_lev,...
        'Titles', tit_lev,...
        'LegendsNames',{MODEL.esc_names{2}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    % Brechas
    PostPrGaps(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','PostProcessing'),...
        'Esc_add', {'v6', MODEL.PostProc.v6, MODEL.esc_col{2}},...
        'PlotList', list_gaps,...
        'LegendsNames',{MODEL.esc_names{2}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    
    % Descomposición de choques para variables seleccionadas
    list = {'L_GDP_RW_GAP', 'DLA_CPI_RW', 'RS_RW', 'D4L_CPI_NOSUBY','L_GDP_GAP','DLA_CPIXFE', 'DLA_S', 'D4L_MB', 'RS',...
            'D4L_CPI', 'L_Z_GAP', 'D4L_VEL', 'RR', 'D4L_S', 'RMC', 'MCI'};
    
    % Long
    plot_shd_dsc(MODEL, MODEL.Esc.v6.pred, MODEL.Esc.v6.shd,...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','Shock_dec\long'),...
        'Rng', {},...
        'Variables',list)

    %short
    plot_shd_dsc(MODEL, MODEL.Esc.v6.pred, MODEL.Esc.v6.shd,...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','Shock_dec\short'),...
        'Rng', MODEL.DATES.hist_end-20:MODEL.DATES.hist_end+20,...
        'Variables',list)
    
    % Descomposición de chosques para variables seleccionadas
    % (Primeras diferencias)
    plot_diff_shd_dsc(MODEL,...
                  'variables', list,...
                  'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v6', 'Shock_dec', 'diff'),...
                  'Esc_add', {'v6', MODEL.Esc.v6.shd, MODEL.Esc.v6.pred});
    
    % Contribuciones
    contributions(MODEL,...
        'Esc_add', {'v6', MODEL.Esc.v6.pred}, ... 
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v6', 'contributions') ...           
    );
              
    contributions(MODEL,...
        'Esc_add', {'v6', MODEL.Esc.v6.pred}, ... 
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v6', 'diff_contributions'), ... 
        'Difference', true ...
    );         
    
    % Real exchange rate (subplot)
    tcr_subplot(MODEL,...
        'Esc_add', {'v6', MODEL.Esc.v6.pred, MODEL.esc_col{2}},...
        'tab_range', tab_range,...
        'LegendsNames',{MODEL.esc_names{2}, MODEL.leg_act});
    
    % Money Velocity (subplot)
    vel_subplot(MODEL,...
        'tab_range', tab_range,...
        'Esc_add', {'v6', MODEL.PostProc, MODEL.esc_col{2}},...
        'tab_range', tab_range,...
        'LegendsNames',{MODEL.esc_names{2}, MODEL.leg_act},...
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v6', 'otras'));
end
disp('Escenario 6: ok');