%% Escenario alterno 6
%{
    Escenarios donde se anclan los pronósticos de la brecha del DAMP, 
    debido a que el fin de historia del pib y el fin de historia del
    modelo no es el mismo, para el anclaje del trimestre historico del pib
    que no se tiene se realizan los calculos de todas las variables (L_GDP_GAP, L_GDP, D4L_GDP, S4L_GD, D4S4L_GDP) con el
    pronóstico del DAMP y anclar luego del plan de simulación, y en el postprocessing se anclan las variabls L_GDP_GAP y L_GDP
    para ese trimestre de des fase. Esto se realiza de esta forma ya que ese trimestre de la brecha del PIB no tiene influencia sobre 
    ninguna otra variable según las ecuaciones del modelo para ese trimestre al ya ser historia en el resto de variables.
     
%}

%% Anclaje de tasa de interes de fondos federales y PCE CORE
% (Anclaje hasta 2025Q4)

% Base de datos
alt6 = databank.fromCSV(...
        fullfile('data', 'corrimientos',MODEL.CORR_DATE,...
                 'v6', 'fulldata_brecha.csv')); 
             
% Trimestres de anclaje
MODEL.DATES.E6_dates = MODEL.DATES.pred_start:MODEL.DATES.pred_start+4;

%MODEL.DATES.E6_dates = MODEL.DATES.pred_start;

%% %%%%%%%%%%%%%%%% Creación de escenario alternativo %%%%%%%%%%%%%%%%%%%%%%
% Shocks del escenario base
shocks = MODEL.F*get(MODEL.MF, 'elist');
% Concatenación de bd con condiciones iniciales (MODEL.F) y shocks Esc.
% Libre
MODEL.Esc.v6.dbi = dboverlay(MODEL.F,shocks);

% Anclaje de último valor observado mensual
% Tipo de Cambio Nominal
% MODEL.Esc.v6.dbi.D4L_S(MODEL.DATES.E6_dates) = MODEL.PreProc.monthly.S.log.diff(-12).data(end)*100;

% Anclaje de brecha
MODEL.Esc.v6.dbi.L_GDP_GAP(MODEL.DATES.E6_dates) = alt6.gap(MODEL.DATES.E6_dates);

% GDP
% [~, GDP_gap] = hpf(alt6.gdp); 
% MODEL.Esc.v6.dbi.L_GDP_GAP(MODEL.DATES.E6_dates_GDP) = GDP_gap(MODEL.DATES.E6_dates_GDP);

%% Creación de plan de simulación
% Variables
vars = {'L_GDP_GAP'};

% choques
s_vars = {'SHK_L_GDP_GAP'};

% Plan de simulación
MODEL.Esc.v6.planSim = plan(MODEL.MF, MODEL.DATES.pred_start:MODEL.DATES.pred_end);
% Variable a endogenizar (shock propio?? No necesariamente)
MODEL.Esc.v6.planSim = endogenize(MODEL.Esc.v6.planSim,s_vars,MODEL.DATES.E6_dates); 
% Variable a exogenizar (Anclaje)
MODEL.Esc.v6.planSim = exogenize(MODEL.Esc.v6.planSim,vars,MODEL.DATES.E6_dates);

%% Anclaje de pronóstico de la brecha del DAMP de 2024Q3
%Esto se debe a que el fin de historia del PIB tiene un rezago extra a las
%demas variables
MODEL.Esc.v6.dbi.L_GDP_GAP(MODEL.DATES.pred_start-1) = alt6.gap(MODEL.DATES.pred_start-1);
MODEL.Esc.v6.dbi.L_GDP(MODEL.DATES.pred_start-1) = alt6.logpib(MODEL.DATES.pred_start-1);
MODEL.Esc.v6.dbi.D4L_GDP(MODEL.DATES.pred_start-1) = alt6.d4lpib(MODEL.DATES.pred_start-1);
MODEL.Esc.v6.dbi.S4L_GDP(MODEL.DATES.pred_start-1) = alt6.sumlogpib(MODEL.DATES.pred_start-1);
MODEL.Esc.v6.dbi.D4S4L_GDP(MODEL.DATES.pred_start-1) = alt6.d4lsumlogpib(MODEL.DATES.pred_start-1);
%% Simulación.
MODEL.Esc.v6.pred = simulate(MODEL.MF,...
                  MODEL.Esc.v6.dbi,...
                  MODEL.DATES.pred_start:MODEL.DATES.pred_end,...
                  'plan',MODEL.Esc.v6.planSim,...
                  'anticipate',false,...
                  'DbOverlay=', true);

% Descomposición             
MODEL.Esc.v6.shd = simulate(MODEL.MF,...
                  MODEL.Esc.v6.pred,...
                  MODEL.DATES.hist_start:MODEL.DATES.pred_end,...
                  'anticipate',false,...
                  'contributions',true);



%% Post-Procesamiento de variables seleccionadas.
pp_list = {'L_MB', 'L_VEL', 'L_CPI_RW', 'L_IPEI_Q','L_Z', 'L_GDP', 'L_GDP_RW'};
list_nivel = {'L_S','L_MB'};
                                        
MODEL = rec_GDP_RW(MODEL, 'Esc', 'v6');

MODEL = PostProcessing(MODEL,...
    'list',pp_list,...
    'list_niv', list_nivel,...
    'Esc',{'v6', MODEL.Esc.v6.pred})

%Anclaje de brecha del pib en el post processing para el trimestre rezagado para el cual no hay
%historia
MODEL.PostProc.v6.l_gap.L_GDP_GAP(MODEL.DATES.pred_start-1) = alt6.gap(MODEL.DATES.pred_start-1);
MODEL.Esc.v6.dbi.L_GDP(MODEL.DATES.pred_start-1) = alt6.logpib(MODEL.DATES.pred_start-1);
%% Graficas

if graph_esc == true
    % Pre-processing
    % monthly
    PreProcPlots_m(MODEL,...
        'Esc_add', {'v6', MODEL_ANT},...
        'tab_range_mm', tab_range_mm);
    
    % quarterly
    PreProcPlots_q(MODEL,...
        'Esc_add', {'v6', MODEL_ANT},...
        'tab_range', tab_range_source_data)
    % Graficas de simulación
    simPlots(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','prediction_compared'),...}
        'Esc_add', {'v6', MODEL.Esc.v6.pred, MODEL.esc_col{6}},...
        'PlotList', get(MODEL.MF, 'xlist'),...
        'LegendsNames',{MODEL.esc_names{7}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    
    % Post Procesamiento
    % Logaritmo/tendencia vs corr. Anterior
    PostPrLogsComp(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE,'v6', 'PostProcessing'),...
        'Esc',{'v0', MODEL.PostProc},...
        'Esc_add', {'v6', MODEL.PostProc.v6, MODEL.esc_col{6}},...
        'PlotList', pp_list,...
        'LegendsNames',{MODEL.esc_names{7}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    % Variables en Niveles originales
    PostPrLevels(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','PostProcessing'),...
        'Esc_add', {'v6', MODEL.PostProc.v6, MODEL.esc_col{6}},...
        'PlotList', list_lev,...
        'Titles', tit_lev,...
        'LegendsNames',{MODEL.esc_names{7}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    % Brechas
    PostPrGaps(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','PostProcessing'),...
        'Esc_add', {'v6', MODEL.PostProc.v6, MODEL.esc_col{6}},...
        'PlotList', list_gaps,...
        'LegendsNames',{MODEL.esc_names{7}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    
    % Descomposición de choques para variables seleccionadas
    list = {'L_GDP_RW_GAP', 'DLA_CPI_RW', 'RS_RW', 'D4L_CPI_NOSUBY','L_GDP_GAP','DLA_CPIXFE', 'DLA_S', 'D4L_MB', 'RS',...
            'D4L_CPI', 'L_Z_GAP', 'D4L_VEL', 'RR', 'D4L_S', 'RMC', 'MCI'};
    
    % Long
    plot_shd_dsc(MODEL, MODEL.Esc.v6.pred, MODEL.Esc.v6.shd,...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','Shock_dec\long'),...
        'Rng', {},...
        'Variables',list)

    %short
    plot_shd_dsc(MODEL, MODEL.Esc.v6.pred, MODEL.Esc.v6.shd,...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','Shock_dec\short'),...
        'Rng', MODEL.DATES.hist_end-20:MODEL.DATES.hist_end+20,...
        'Variables',list)
    
    % Descomposición de chosques para variables seleccionadas
    % (Primeras diferencias)
    plot_diff_shd_dsc(MODEL,...
                  'variables', list,...
                  'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v6', 'Shock_dec', 'diff'),...
                  'Esc_add', {'v6', MODEL.Esc.v6.shd, MODEL.Esc.v6.pred});
    
    % Contribuciones
    contributions(MODEL,...
        'Esc_add', {'v6', MODEL.Esc.v6.pred}, ... 
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v6', 'contributions') ...           
    );
              
    contributions(MODEL,...
        'Esc_add', {'v6', MODEL.Esc.v6.pred}, ... 
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v6', 'diff_contributions'), ... 
        'Difference', true ...
    );               
    
    % Real exchange rate (subplot)
    tcr_subplot(MODEL,...
        'Esc_add', {'v6', MODEL.Esc.v6.pred, MODEL.esc_col{6}},...
        'tab_range', tab_range,...
        'LegendsNames',{MODEL.esc_names{7}, MODEL.leg_act});
    
    % Money Velocity (subplot)
    vel_subplot(MODEL,...
        'tab_range', tab_range,...
        'Esc_add', {'v6', MODEL.PostProc, MODEL.esc_col{6}},...
        'tab_range', tab_range,...
        'LegendsNames',{MODEL.esc_names{7}, MODEL.leg_act},...
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v6', 'otras'));
end
disp('Escenario 6: ok');




