%{
Creación de escenarios modificando el estados estacionario de las remesas
de 15 a 19 en pasos de 0.10 para encontrar una brecha que cierre después de
dos años pero no mayor a 5
%}

%% Lista de estados estacionarios a evaluar
ss_rem_gdp = [17:0.1:19];

%% Generación de modelos a utilizar
% parámetros del QPM
setparam;

% Carga del modelo
for i = 1:length(ss_rem_gdp)
    
    ss = s;
    ss.ss_REM_GDP = ss_rem_gdp(i);
    M = model(MODEL.mod_file_name, 'assign', ss);
    M = sstate(M,'growth=',true,'MaxFunEvals',1000,'display=','off');
    M = solve(M,'error=',true);
    
    fieldName = sprintf('rem_%d', i);
    model_name = sprintf('rem_%d', i);
    
    MODEL.Esc_rem.(fieldName).MODEL = M;
    MODEL.Esc_rem.(fieldName).name = model_name;
    
end

%Filtro de kalman para cada modelo

for i = 1:length(ss_rem_gdp)
    
    fieldName = sprintf('rem_%d', i);
    [MODEL.Esc_rem.(fieldName).MF, MODEL.Esc_rem.(fieldName).F] = filter(MODEL.Esc_rem.(fieldName).MODEL, MODEL.PreProc.obs,... 
                                MODEL.DATES.hist_start:MODEL.DATES.hist_end, ... 
                                'meanOnly=',true);
end

% Pronosticos para cada modelo

fcstrng = MODEL.DATES.pred_start:MODEL.DATES.pred_end;

for i = 1:length(ss_rem_gdp)
    
    fieldName = sprintf('rem_%d', i);
    MODEL.Esc_rem.(fieldName).F_pred = simulate(MODEL.Esc_rem.(fieldName).MF,... Modelo Filtrado
                            MODEL.Esc_rem.(fieldName).F,...Base de datos inicial filtrada
                            fcstrng,... Rango de Simulación
                            'anticipate', false,...
                            'DbOverlay=', true);

end
                    
for i = 1:length(ss_rem_gdp)
    
    fieldName = sprintf('rem_%d', i);
    plot(qq(2024,1):qq(2032,1),...
        MODEL.Esc_rem.(fieldName).F_pred.L_GDP_GAP);
    
    hold on
    
    zeroline();

end

%% Selección del modelo
% Se seleccionó un estado estacionario de 19% debido a que cierra la brecha
% antes de 5 años despúes de los pronósticos y con valores razonables.

% Modelo
MODEL.Esc.v6.MODEL = MODEL.Esc_rem.rem_19.MODEL;
MODEL.Esc.v6.MF = MODEL.Esc_rem.rem_19.MF;
MODEL.Esc.v6.F = MODEL.Esc_rem.rem_19.F;
MODEL.Esc.v6.pred = MODEL.Esc_rem.rem_19.F_pred;

% Descomposición de shocks
MODEL.Esc.v6.shd = simulate(MODEL.Esc.v6.MF,...
                  MODEL.Esc.v6.pred,...
                  MODEL.DATES.hist_start:MODEL.DATES.pred_end,...
                  'anticipate',false,...
                  'contributions',true);

% Post-Procesamiento de variables seleccionadas.
% Desestacionalizar y obtener brechas y tendencias de estas variables
pp_list = {'L_MB', 'L_VEL', 'L_CPI_RW', 'L_IPEI_Q','L_Z', 'L_GDP', 'L_GDP_RW'};
% Recuperar niveles de estas variables
list_nivel = {'L_S','L_MB'};
                                        
MODEL = rec_GDP_RW(MODEL, 'Esc', 'v6');

MODEL = PostProcessing(MODEL,...
    'list',pp_list,...
    'list_niv', list_nivel,...
    'Esc',{'v6', MODEL.Esc.v6.pred});

%% Graficas
graph_esc = true;
if graph_esc == true
    % Pre-processing
    % monthly
    PreProcPlots_m(MODEL,...
        'Esc_add', {'v6', MODEL_ANT},...
        'tab_range_mm', tab_range_mm);
    
    % quarterly
    PreProcPlots_q(MODEL,...
        'Esc_add', {'v6', MODEL_ANT},...
        'tab_range', tab_range_source_data)
    % Graficas de simulación
    simPlots(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','prediction_compared'),...}
        'Esc_add', {'v6', MODEL.Esc.v6.pred, MODEL.esc_col{6}},...
        'PlotList', get(MODEL.MF, 'xlist'),...
        'LegendsNames',{MODEL.esc_names{7}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    
    % Post Procesamiento
    % Logaritmo/tendencia vs corr. Anterior
    PostPrLogsComp(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE,'v6', 'PostProcessing'),...
        'Esc',{'v0', MODEL.PostProc},...
        'Esc_add', {'v6', MODEL.PostProc.v6, MODEL.esc_col{6}},...
        'PlotList', pp_list,...
        'LegendsNames',{MODEL.esc_names{7}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    % Variables en Niveles originales
    PostPrLevels(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','PostProcessing'),...
        'Esc_add', {'v6', MODEL.PostProc.v6, MODEL.esc_col{6}},...
        'PlotList', list_lev,...
        'Titles', tit_lev,...
        'LegendsNames',{MODEL.esc_names{7}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    % Brechas
    PostPrGaps(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','PostProcessing'),...
        'Esc_add', {'v6', MODEL.PostProc.v6, MODEL.esc_col{6}},...
        'PlotList', list_gaps,...
        'LegendsNames',{MODEL.esc_names{7}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    
    % Descomposición de choques para variables seleccionadas
    list = {'L_GDP_RW_GAP', 'DLA_CPI_RW', 'RS_RW', 'D4L_CPI_NOSUBY','L_GDP_GAP','DLA_CPIXFE', 'DLA_S', 'D4L_MB', 'RS',...
            'D4L_CPI', 'L_Z_GAP', 'D4L_VEL', 'RR', 'D4L_S', 'RMC', 'MCI'};
    
    % Long
    plot_shd_dsc(MODEL, MODEL.Esc.v6.pred, MODEL.Esc.v6.shd,...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','Shock_dec\long'),...
        'Rng', {},...
        'Variables',list)

    %short
    plot_shd_dsc(MODEL, MODEL.Esc.v6.pred, MODEL.Esc.v6.shd,...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','Shock_dec\short'),...
        'Rng', MODEL.DATES.hist_end-20:MODEL.DATES.hist_end+20,...
        'Variables',list)
    
    % Descomposición de chosques para variables seleccionadas
    % (Primeras diferencias)
    plot_diff_shd_dsc(MODEL,...
                  'variables', list,...
                  'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v6', 'Shock_dec', 'diff'),...
                  'Esc_add', {'v6', MODEL.Esc.v6.shd, MODEL.Esc.v6.pred});
    
    % Contribuciones
    contributions(MODEL,...
        'Esc_add', {'v6', MODEL.Esc.v6.pred}, ... 
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v6', 'contributions') ...           
    );
              
    contributions(MODEL,...
        'Esc_add', {'v6', MODEL.Esc.v6.pred}, ... 
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v6', 'diff_contributions'), ... 
        'Difference', true ...
    );         
    
    % Real exchange rate (subplot)
    tcr_subplot(MODEL,...
        'Esc_add', {'v6', MODEL.Esc.v6.pred, MODEL.esc_col{6}},...
        'tab_range', tab_range,...
        'LegendsNames',{MODEL.esc_names{7}, MODEL.leg_act});
    
    % Money Velocity (subplot)
    vel_subplot(MODEL,...
        'tab_range', tab_range,...
        'Esc_add', {'v6', MODEL.PostProc, MODEL.esc_col{6}},...
        'tab_range', tab_range,...
        'LegendsNames',{MODEL.esc_names{7}, MODEL.leg_act},...
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v6', 'otras'));
end
disp('Escenario 6: ok');

