%{
Se prueba las remesas para distintos valores de Rho para la convergencia
del de la brecha a su estado estacionario. Para este ejercicio se dejó el
estado estacionario en 15% del PIB.
%}

%% Lista de estados rho_rem_gdp a evaluar
rho_rem_gdp = [0.70:0.01:0.99];

%% Generación de modelos a utilizar
% parámetros del QPM
setparam;

% Carga del modelo
for i = 1:length(rho_rem_gdp)
    
    ss = s;
    ss.rho_REM_GDP = rho_rem_gdp(i);
    M = model(MODEL.mod_file_name, 'assign', ss);
    M = sstate(M,'growth=',true,'MaxFunEvals',1000,'display=','off');
    M = solve(M,'error=',true);
    
    fieldName = sprintf('rem_rho_%d', i);
    model_name = sprintf('rem_rho_%d', i);
    
    MODEL.Esc_rem_rho.(fieldName).MODEL = M;
    MODEL.Esc_rem_rho.(fieldName).name = model_name;
    
end


%Filtro de kalman para cada modelo
for i = 1:length(rho_rem_gdp)
    
    fieldName = sprintf('rem_rho_%d', i);
    [MODEL.Esc_rem_rho.(fieldName).MF, MODEL.Esc_rem_rho.(fieldName).F] = filter(MODEL.Esc_rem_rho.(fieldName).MODEL, MODEL.PreProc.obs,... 
                                MODEL.DATES.hist_start:MODEL.DATES.hist_end, ... 
                                'meanOnly=',true);
end

% Pronosticos para cada modelo
fcstrng = MODEL.DATES.pred_start:MODEL.DATES.pred_end;

for i = 1:length(rho_rem_gdp)
    
    fieldName = sprintf('rem_rho_%d', i);
    MODEL.Esc_rem_rho.(fieldName).F_pred = simulate(MODEL.Esc_rem_rho.(fieldName).MF,... Modelo Filtrado
                            MODEL.Esc_rem_rho.(fieldName).F,...Base de datos inicial filtrada
                            fcstrng,... Rango de Simulación
                            'anticipate', false,...
                            'DbOverlay=', true);

end


%% Selección del modelo
% Se seleccionó un valor de rho_rem_gdp de 0.73 dentro del proceso AR de
% las Remesas

% Modelo
MODEL.Esc.v7.MODEL = MODEL.Esc_rem_rho.rem_rho_3.MODEL;
MODEL.Esc.v7.MF = MODEL.Esc_rem_rho.rem_rho_3.MF;
MODEL.Esc.v7.F = MODEL.Esc_rem_rho.rem_rho_3.F;
MODEL.Esc.v7.pred = MODEL.Esc_rem_rho.rem_rho_3.F_pred;

% Descomposición de shocks
MODEL.Esc.v7.shd = simulate(MODEL.Esc.v7.MF,...
                  MODEL.Esc.v7.pred,...
                  MODEL.DATES.hist_start:MODEL.DATES.pred_end,...
                  'anticipate',false,...
                  'contributions',true);

% Post-Procesamiento de variables seleccionadas.
% Desestacionalizar y obtener brechas y tendencias de estas variables
pp_list = {'L_MB', 'L_VEL', 'L_CPI_RW', 'L_IPEI_Q','L_Z', 'L_GDP', 'L_GDP_RW'};
% Recuperar niveles de estas variables
list_nivel = {'L_S','L_MB'};
                                        
MODEL = rec_GDP_RW(MODEL, 'Esc', 'v7');

MODEL = PostProcessing(MODEL,...
    'list',pp_list,...
    'list_niv', list_nivel,...
    'Esc',{'v7', MODEL.Esc.v7.pred});

%% Graficas
graph_esc = true;
if graph_esc == true
    % Pre-processing
    % monthly
    PreProcPlots_m(MODEL,...
        'Esc_add', {'v7', MODEL_ANT},...
        'tab_range_mm', tab_range_mm);
    
    % quarterly
    PreProcPlots_q(MODEL,...
        'Esc_add', {'v7', MODEL_ANT},...
        'tab_range', tab_range_source_data)
    % Graficas de simulación
    simPlots(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v7','prediction_compared'),...}
        'Esc_add', {'v7', MODEL.Esc.v7.pred, MODEL.esc_col{7}},...
        'PlotList', get(MODEL.MF, 'xlist'),...
        'LegendsNames',{MODEL.esc_names{8}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    
    % Post Procesamiento
    % Logaritmo/tendencia vs corr. Anterior
    PostPrLogsComp(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE,'v7', 'PostProcessing'),...
        'Esc',{'v0', MODEL.PostProc},...
        'Esc_add', {'v7', MODEL.PostProc.v7, MODEL.esc_col{7}},...
        'PlotList', pp_list,...
        'LegendsNames',{MODEL.esc_names{8}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    % Variables en Niveles originales
    PostPrLevels(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v7','PostProcessing'),...
        'Esc_add', {'v7', MODEL.PostProc.v7, MODEL.esc_col{7}},...
        'PlotList', list_lev,...
        'Titles', tit_lev,...
        'LegendsNames',{MODEL.esc_names{8}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    % Brechas
    PostPrGaps(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v7','PostProcessing'),...
        'Esc_add', {'v7', MODEL.PostProc.v7, MODEL.esc_col{7}},...
        'PlotList', list_gaps,...
        'LegendsNames',{MODEL.esc_names{8}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    
    % Descomposición de choques para variables seleccionadas
    list = {'L_GDP_RW_GAP', 'DLA_CPI_RW', 'RS_RW', 'D4L_CPI_NOSUBY','L_GDP_GAP','DLA_CPIXFE', 'DLA_S', 'D4L_MB', 'RS',...
            'D4L_CPI', 'L_Z_GAP', 'D4L_VEL', 'RR', 'D4L_S', 'RMC', 'MCI'};
    
    % Long
    plot_shd_dsc(MODEL, MODEL.Esc.v7.pred, MODEL.Esc.v7.shd,...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v7','Shock_dec\long'),...
        'Rng', {},...
        'Variables',list)

    %short
    plot_shd_dsc(MODEL, MODEL.Esc.v7.pred, MODEL.Esc.v7.shd,...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v7','Shock_dec\short'),...
        'Rng', MODEL.DATES.hist_end-20:MODEL.DATES.hist_end+20,...
        'Variables',list)
    
    % Descomposición de chosques para variables seleccionadas
    % (Primeras diferencias)
    plot_diff_shd_dsc(MODEL,...
                  'variables', list,...
                  'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v7', 'Shock_dec', 'diff'),...
                  'Esc_add', {'v7', MODEL.Esc.v7.shd, MODEL.Esc.v7.pred});
    
    % Contribuciones
    contributions(MODEL,...
        'Esc_add', {'v7', MODEL.Esc.v7.pred}, ... 
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v7', 'contributions') ...           
    );
              
    contributions(MODEL,...
        'Esc_add', {'v7', MODEL.Esc.v7.pred}, ... 
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v7', 'diff_contributions'), ... 
        'Difference', true ...
    );         
    
    % Real exchange rate (subplot)
    tcr_subplot(MODEL,...
        'Esc_add', {'v7', MODEL.Esc.v7.pred, MODEL.esc_col{7}},...
        'tab_range', tab_range,...
        'LegendsNames',{MODEL.esc_names{8}, MODEL.leg_act});
    
    % Money Velocity (subplot)
    vel_subplot(MODEL,...
        'tab_range', tab_range,...
        'Esc_add', {'v7', MODEL.PostProc, MODEL.esc_col{7}},...
        'tab_range', tab_range,...
        'LegendsNames',{MODEL.esc_names{8}, MODEL.leg_act},...
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v7', 'otras'));
end
disp('Escenario 7: ok');
