%% Escenario alterno 6
%{
    Escenarios de riesgo alrededor de variables externas o que no son
    instrumentos de Política Monetaria.

    Este Escenario: Se anclan pronósticos de la tasa de interes de fondos federales. 
    Se usan los pronósticos  provenientes del FOMC (se anclan los
    pronósticos medios de la Federal funds rate)
%}

%% Anclaje de variables externas 
% (Anclaje hasta 2025Q4)

% Base de datos
alt6 = databank.fromCSV(...
        fullfile('data', 'corrimientos',MODEL.CORR_DATE,...
                 'v6', 'fulldata_EXT.csv')); 
             
% Trimestres de anclaje
MODEL.DATES.E6_dates = MODEL.DATES.pred_start:MODEL.DATES.pred_start+5;

%% %%%%%%%%%%%%%%%% Creación de escenario alternativo %%%%%%%%%%%%%%%%%%%%%%
% Shocks del escenario base
shocks = MODEL.F*get(MODEL.MF, 'elist');
% Concatenación de bd con condiciones iniciales (MODEL.F) y shocks Esc.
% Libre
MODEL.Esc.v6.dbi = dboverlay(MODEL.F,shocks);

% Imposición de anclajes provenientes del FOMC últimos pronósticos
% publicados
MODEL.Esc.v6.dbi.RS_RW(MODEL.DATES.E6_dates) = alt6.istar(MODEL.DATES.E6_dates);
MODEL.Esc.v6.dbi.D4L_CPI_RW(MODEL.DATES.E6_dates) = alt6.pceus(MODEL.DATES.E6_dates);

MODEL.Esc.v6.dbi.GDP_RW = MODEL.PreProc.quarterly.GDP_RW; 
MODEL.Esc.v6.dbi.GDP_RW(MODEL.DATES.E6_dates) = alt6.gdpus(MODEL.DATES.E6_dates);
MODEL.Esc.v6.dbi.L_GDP_RW = MODEL.Esc.v6.dbi.GDP_RW.log*100; 

% % --- Método de Pronosticar tendencia con ARIMA ---
% % Modelo ARIMA(1,1,0) para la tendencia 
% md = arima(1,1,0);
% estmd = estimate(md, MODEL.PreProc.quarterly.L_GDP_RW_BAR.Data);
% fcstrng = length(MODEL.PreProc.quarterly.L_GDP_RW.End+1:MODEL.DATES.pred_end);
% % Se pronostica tendencia 
% [Y, ~] = forecast(estmd,  fcstrng, MODEL.PreProc.quarterly.L_GDP_RW_BAR.Data);
% % Se obtiene la tendencia durante el período de anclaje
% MODEL.Esc.v6.dbi.L_GDP_RW_BAR = MODEL.PreProc.quarterly.L_GDP_RW_BAR;
% MODEL.Esc.v6.dbi.L_GDP_RW_BAR(MODEL.PreProc.quarterly.L_GDP_RW.End+1:MODEL.DATES.pred_end) = Y;
% % Calculamos brecha en período completo (historia + anclaje)
% MODEL.Esc.v6.dbi.L_GDP_RW_GAP = MODEL.Esc.v6.dbi.L_GDP_RW - MODEL.Esc.v6.dbi.L_GDP_RW_BAR; 

% --- Versión sin arima --- 
% MODEL.Esc.v6.dbi.L_GDP_RW_BAR = MODEL.Esc.v6.dbi.L_GDP_RW.hpf; 
% MODEL.Esc.v6.dbi.L_GDP_RW_GAP = MODEL.Esc.v6.dbi.L_GDP_RW - MODEL.Esc.v6.dbi.L_GDP_RW_BAR; 
[~, MODEL.Esc.v6.dbi.L_GDP_RW_GAP] = hpf(MODEL.Esc.v6.dbi.L_GDP_RW); 
% Arreglamos período de historia poniendo los datos originales
MODEL.Esc.v6.dbi.L_GDP_RW_GAP(MODEL.DATES.hist_start:MODEL.DATES.hist_end) = MODEL.F.L_GDP_RW_GAP(MODEL.DATES.hist_start:MODEL.DATES.hist_end);


%% Creación de plan de simulación
% Variables
vars = {'RS_RW','D4L_CPI_RW','L_GDP_RW_GAP'};
% choques
s_vars = {'SHK_RS_RW','SHK_DLA_CPI_RW','SHK_L_GDP_RW_GAP'};

% Plan de simulación
MODEL.Esc.v6.planSim = plan(MODEL.MF, MODEL.DATES.pred_start:MODEL.DATES.pred_end);
% Variable a endogenizar (shock propio?? No necesariamente)
MODEL.Esc.v6.planSim = endogenize(MODEL.Esc.v6.planSim,s_vars,MODEL.DATES.E6_dates); 
% Variable a exogenizar (Anclaje)
MODEL.Esc.v6.planSim = exogenize(MODEL.Esc.v6.planSim,vars,MODEL.DATES.E6_dates);

%% Simulación.
MODEL.Esc.v6.pred = simulate(MODEL.MF,...
                  MODEL.Esc.v6.dbi,...
                  MODEL.DATES.pred_start:MODEL.DATES.pred_end,...
                  'plan',MODEL.Esc.v6.planSim,...
                  'anticipate',false,...
                  'DbOverlay=', true);

% Descomposición             
MODEL.Esc.v6.shd = simulate(MODEL.MF,...
                  MODEL.Esc.v6.pred,...
                  MODEL.DATES.hist_start:MODEL.DATES.pred_end,...
                  'anticipate',false,...
                  'contributions',true);



%% Post-Procesamiento de variables seleccionadas.
pp_list = {'L_MB', 'L_VEL', 'L_CPI_RW', 'L_IPEI_Q','L_Z', 'L_GDP', 'L_GDP_RW'};
list_nivel = {'L_S','L_MB'};
                                        
MODEL = rec_GDP_RW(MODEL, 'Esc', 'v6');

MODEL = PostProcessing(MODEL,...
    'list',pp_list,...
    'list_niv', list_nivel,...
    'Esc',{'v6', MODEL.Esc.v6.pred});

%% Graficas

if graph_esc == true
    % Pre-processing
    % monthly
    PreProcPlots_m(MODEL,...
        'Esc_add', {'v6', MODEL_ANT},...
        'tab_range_mm', tab_range_mm);
    
    % quarterly
    PreProcPlots_q(MODEL,...
        'Esc_add', {'v6', MODEL_ANT},...
        'tab_range', tab_range_source_data)
    % Graficas de simulación
    simPlots(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','prediction_compared'),...}
        'Esc_add', {'v6', MODEL.Esc.v6.pred, MODEL.esc_col{6}},...
        'PlotList', get(MODEL.MF, 'xlist'),...
        'LegendsNames',{MODEL.esc_names{7}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    
    % Post Procesamiento
    % Logaritmo/tendencia vs corr. Anterior
    PostPrLogsComp(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE,'v6', 'PostProcessing'),...
        'Esc',{'v0', MODEL.PostProc},...
        'Esc_add', {'v6', MODEL.PostProc.v6, MODEL.esc_col{6}},...
        'PlotList', pp_list,...
        'LegendsNames',{MODEL.esc_names{7}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    % Variables en Niveles originales
    PostPrLevels(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','PostProcessing'),...
        'Esc_add', {'v6', MODEL.PostProc.v6, MODEL.esc_col{6}},...
        'PlotList', list_lev,...
        'Titles', tit_lev,...
        'LegendsNames',{MODEL.esc_names{7}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    % Brechas
    PostPrGaps(MODEL,...
        'StartDate',{MODEL.DATES.hist_start, MODEL.DATES.hist_end - 20},...
        'EndDatePlot', {MODEL.DATES.pred_end, MODEL.DATES.hist_end + 20},...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','PostProcessing'),...
        'Esc_add', {'v6', MODEL.PostProc.v6, MODEL.esc_col{6}},...
        'PlotList', list_gaps,...
        'LegendsNames',{MODEL.esc_names{7}, MODEL.leg_act},...
        'TabRange', tab_range...
        );
    
    % Descomposición de choques para variables seleccionadas
    list = {'L_GDP_RW_GAP', 'DLA_CPI_RW', 'RS_RW', 'D4L_CPI_NOSUBY','L_GDP_GAP','DLA_CPIXFE', 'DLA_S', 'D4L_MB', 'RS',...
            'D4L_CPI', 'L_Z_GAP', 'D4L_VEL', 'RR', 'D4L_S', 'RMC', 'MCI'};
    
    % Long
    plot_shd_dsc(MODEL, MODEL.Esc.v6.pred, MODEL.Esc.v6.shd,...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','Shock_dec\long'),...
        'Rng', {},...
        'Variables',list)

    %short
    plot_shd_dsc(MODEL, MODEL.Esc.v6.pred, MODEL.Esc.v6.shd,...
        'SavePath', fullfile(cd, 'plots', MODEL.CORR_DATE, 'v6','Shock_dec\short'),...
        'Rng', MODEL.DATES.hist_end-20:MODEL.DATES.hist_end+20,...
        'Variables',list)
    
    % Descomposición de chosques para variables seleccionadas
    % (Primeras diferencias)
    plot_diff_shd_dsc(MODEL,...
                  'variables', list,...
                  'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v6', 'Shock_dec', 'diff'),...
                  'Esc_add', {'v6', MODEL.Esc.v6.shd, MODEL.Esc.v6.pred});
    
    % Contribuciones
    contributions(MODEL,...
        'Esc_add', {'v6', MODEL.Esc.v6.pred}, ... 
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v6', 'contributions') ...           
    );
              
    contributions(MODEL,...
        'Esc_add', {'v6', MODEL.Esc.v6.pred}, ... 
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v6', 'diff_contributions'), ... 
        'Difference', true ...
    );               
    
    % Real exchange rate (subplot)
    tcr_subplot(MODEL,...
        'Esc_add', {'v6', MODEL.Esc.v6.pred, MODEL.esc_col{6}},...
        'tab_range', tab_range,...
        'LegendsNames',{MODEL.esc_names{7}, MODEL.leg_act});
    
    % Money Velocity (subplot)
    vel_subplot(MODEL,...
        'tab_range', tab_range,...
        'Esc_add', {'v6', MODEL.PostProc, MODEL.esc_col{6}},...
        'tab_range', tab_range,...
        'LegendsNames',{MODEL.esc_names{7}, MODEL.leg_act},...
        'SavePath', fullfile('plots', MODEL.CORR_DATE, 'v6', 'otras'));
end
disp('Escenario 6: ok');




